# Generated by Django 5.1.6 on 2025-03-27 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0006_delete_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_name', models.CharField(blank=True, max_length=128, null=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.componentcpumodel')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.componentgpumodel')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.componentmemorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PC Build',
                'verbose_name_plural': 'PC Builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
