# Generated by Django 5.1.6 on 2025-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategoryModel',
            fields=[
                ('component_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_category_name', models.CharField(max_length=64, unique=True)),
                ('component_category_title', models.CharField(max_length=64)),
                ('component_category_sub_title', models.TextField()),
                ('component_category_description', models.TextField()),
            ],
        ),
    ]
