# Generated by Django 5.1.6 on 2025-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcategorymodel',
            name='component_category_name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
