# Generated by Django 5.1.6 on 2025-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCpuModel',
            fields=[
                ('component_cpu_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CPU ID')),
                ('component_cpu_brand', models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=32, verbose_name='Brand')),
                ('component_cpu_series', models.CharField(max_length=32, verbose_name='Series')),
                ('component_cpu_model', models.CharField(max_length=32, verbose_name='Model')),
                ('component_cpu_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='CPU Name')),
                ('component_cpu_socket', models.CharField(max_length=32, verbose_name='CPU Socket')),
                ('component_cpu_clock_speed', models.DecimalField(decimal_places=1, help_text='CPU clock speed in GHz', max_digits=3)),
                ('component_cpu_cores', models.PositiveIntegerField(verbose_name='Number of Cores')),
                ('component_cpu_threads', models.PositiveIntegerField(verbose_name='Number of Threads')),
                ('component_cpu_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cpu Price')),
                ('component_cpu_image', models.ImageField(default='default_cpu.png', upload_to='components/cpu/', verbose_name='Cpu Image')),
            ],
            options={
                'verbose_name': 'CPU Component',
                'verbose_name_plural': 'CPU Components',
                'unique_together': {('component_cpu_brand', 'component_cpu_series', 'component_cpu_model')},
            },
        ),
    ]
