# Generated by Django 5.1.6 on 2025-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentmemorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGpuModel',
            fields=[
                ('component_gpu_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='GPU ID')),
                ('component_gpu_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='GPU Name')),
                ('component_gpu_brand', models.CharField(max_length=128, verbose_name='GPU Brand')),
                ('component_gpu_model', models.CharField(max_length=128, verbose_name='GPU Model')),
                ('component_gpu_series', models.CharField(max_length=128, verbose_name='GPU Series')),
                ('component_gpu_vram', models.PositiveIntegerField(verbose_name='GPU Memory Size')),
                ('component_gpu_boost_clock', models.PositiveIntegerField(help_text='CPU frequency in MHz', verbose_name='GPU Boost Clock')),
                ('component_gpu_hdmi_port', models.PositiveIntegerField(verbose_name='GPU HDMI Port')),
                ('component_gpu_power_consumption', models.PositiveIntegerField(verbose_name='GPU Power Consumption')),
                ('component_gpu_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='GPU Price')),
            ],
            options={
                'verbose_name': 'GPU Component',
                'verbose_name_plural': 'GPU Components',
                'unique_together': {('component_gpu_brand', 'component_gpu_model')},
            },
        ),
    ]
