# Generated by Django 5.1.6 on 2025-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_componentgpumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentgpumodel',
            name='component_gpu_image',
            field=models.ImageField(default='default_gpu.png', upload_to='components/gpu/', verbose_name='GPU Image'),
        ),
    ]
