# Generated by Django 5.1.6 on 2025-03-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
